return {}
-- return {
--   { -- Autocompletion
--     "hrsh7th/nvim-cmp",
--     event = "InsertEnter",
--     dependencies = {
--       {
--         "L3MON4D3/LuaSnip",
--         build = (function()
--           if vim.fn.has("win32") == 1 or vim.fn.executable("make") == 0 then
--             return
--           end
--           return "make install_jsregexp"
--         end)(),
--         dependencies = {
--           -- {
--           --   "rafamadriz/friendly-snippets",
--           --   config = function()
--           --     require("luasnip.loaders.from_vscode").lazy_load()
--           --   end,
--           -- },
--         },
--       },
--       "saadparwaiz1/cmp_luasnip",
--       "hrsh7th/cmp-nvim-lsp",
--       "hrsh7th/cmp-path",
--       "hrsh7th/cmp-nvim-lsp-signature-help",
--       "onsails/lspkind.nvim",
--     },
--     config = function()
--       local cmp = require("cmp")
--       local luasnip = require("luasnip")
--       local lspkind = require("lspkind")
--       luasnip.config.setup({})
--
--       cmp.setup({
--         preselect = cmp.PreselectMode.None,
--         formatting = {
--           format = lspkind.cmp_format(),
--         },
--         window = {
--           completion = {
--             scrollbar = "║",
--             border = "rounded",
--             winhighlight = "Normal:CmpNormal",
--           },
--           documentation = {
--             border = "rounded",
--             scrollbar = "",
--             winhighlight = "Normal:CmpDocNormal",
--           },
--         },
--         completion = {
--           completeopt = "menu,menuone,noinsert",
--           -- keyword_length = 0,
--           -- autocomplete = false,
--         },
--         mapping = cmp.mapping.preset.insert({
--           ["<C-n>"] = cmp.mapping.select_next_item(),
--           ["<C-p>"] = cmp.mapping.select_prev_item(),
--           ["<C-b>"] = cmp.mapping.scroll_docs(-4),
--           ["<C-f>"] = cmp.mapping.scroll_docs(4),
--           ["<C-y>"] = cmp.mapping.confirm({ select = true }),
--           ["<CR>"] = cmp.mapping.confirm({ select = true }),
--           ["<Tab>"] = cmp.mapping.select_next_item(),
--           ["<S-Tab>"] = cmp.mapping.select_prev_item(),
--           ["<C-Space>"] = cmp.mapping.complete({}),
--           ["<C-l>"] = cmp.mapping(function()
--             if luasnip.expand_or_locally_jumpable() then
--               luasnip.expand_or_jump()
--             end
--           end, { "i", "s" }),
--           ["<C-h>"] = cmp.mapping(function()
--             if luasnip.locally_jumpable(-1) then
--               luasnip.jump(-1)
--             end
--           end, { "i", "s" }),
--         }),
--         sources = {
--           {
--             name = "lazydev",
--             -- set group index to 0 to skip loading LuaLS completions as lazydev recommends it
--             group_index = 0,
--           },
--           { name = "nvim_lsp" },
--           { name = "path" },
--         },
--       })
--     end,
--   },
-- }
-- -- vim: ts=2 sts=2 sw=2 et
