return {
  "stevearc/conform.nvim",
  event = { "BufWritePre" },
  opts = {
    notify_on_error = false,
    formatters_by_ft = {
      astro = { "prettier" },
      sh = { "shfmt" },
      bash = { "shfmt" },
      lua = { "stylua" },
      go = { "goimports", "gofumpt" },
      python = { "ruff_organize_imports", "ruff_format" },
      yaml = { "prettier" },
      json = { "prettier" },
      markdown = { "prettier" },
      javascript = { "prettier" },
      html = { "prettier" },
      css = { "prettier" },
      toml = { "prettier" },
      terraform = { "terraform_fmt" },
      sql = { "sqlfluff" },
      ["*"] = { "trim_newlines", "trim_whitespace" },
    },
    format_on_save = {
      timeout_ms = 500,
      lsp_format = "fallback",
    },
  },
  cmd = { "ConformInfo" },
}
