return {
  'm4xshen/hardtime.nvim',
  event = { 'BufReadPost', 'BufWritePost', 'BufNewFile' },
  dependencies = { 'MunifTanjim/nui.nvim' },
  opts = {
    disable_mouse = false,
    disabled_filetypes = {
      'snacks*',
      'mason*',
      'aerial',
      'alpha',
      'Avante',
      'checkhealth',
      'dapui*',
      'db*',
      'Diffview*',
      'Dressing*',
      'fugitive',
      'help',
      'httpResult',
      'lazy',
      'lspinfo',
      'mason',
      'minifiles',
      'Neogit*',
      'neo%-tree*',
      'neotest%-summary',
      'netrw',
      'noice',
      'notify',
      'NvimTree',
      'oil',
      'prompt',
      'qf',
      'query',
      'TelescopePrompt',
      'Trouble',
      'trouble',
      'VoltWindow',
      'undotree',
      'harpoon*',
    },
  },
}
