return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "css",
      "hcl",
      "html",
      "go",
      "diff",
      "html",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "javascript",
      "jinja",
      "jinja_inline",
      "lua",
      "make",
      "sql",
      "ini",
      "proto",
      "python",
      "query",
      "vim",
      "vimdoc",
      "yaml",
      "toml",
      "json",
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
